### ISSUE TITLE
Add University Of Science And Technology Houari Boumediene Algiers

### ISSUE THREAD

**Issue by mallekbh** [dzcode-io/kuliya#21]
**University/School name**

University Of Science And Technology Houari Boumediene Algiers (USTHB)

**Links/Resources**

- https://www.usthb.dz/fr
- https://en.wikipedia.org/wiki/University_of_Science_and_Technology_Houari_Boumediene

**Comment by ZibanPirate** [comment]
closing as it's done in #27
