### ISSUE TITLE
Add University Of Mouloud Mammri Tizi-Ouzou

### ISSUE THREAD

**Issue by mallekbh** [dzcode-io/kuliya#22]
**University/School name**

University Of Mouloud Mammri Tizi-Ouzou (UMMTO)

**Links/Resources**

- https://www.ummto.dz/
- https://en.wikipedia.org/wiki/University_of_Tizi_Ouzou

**Comment by jumblar** [comment]
Fixed in #26

**Comment by ZibanPirate** [comment]
thanks @jumblar closing as it's fixed in #26
