### ISSUE TITLE
Add University University Mohamed Boudiaf M'sila

### ISSUE THREAD

**Issue by mallekbh** [dzcode-io/kuliya#31]
**University/School name**

University Mohamed Boudiaf - M'sila (UMBM)

**Links/Resources**

- https://www.univ-msila.dz/
- https://fr.wikipedia.org/wiki/Universit%C3%A9_de_M%27Sila 
- https://www.facebook.com/MsilaUniversity/

**Comment by ZibanPirate** [comment]
closing as done in #32
